version: "3.8"
services:
  create-app:
    build:
      dockerfile: dev_app.dockerfile
      args:
        - USER_ID
        - GROUP_ID
      context: .
    image: nlp_demo_dev_app:0.0.1
    command: ["npx", "create-react-app", "/app/$APP_NAME"]
    volumes:
      - "$PWD:/app"

  run-app:
    build:
      dockerfile: dev_app.dockerfile
      args:
        - USER_ID
        - GROUP_ID
      context: .
    ports: 
      - "127.0.0.1:3000:3000"
    image: nlp_demo_dev_app:0.0.1
    init: true
    command: ["/bin/sh", "-c", "npm install && yarn start"]
    working_dir: "/app/$APP_NAME"
    volumes:
      - "$PWD:/app"

  interact-app:
    build: 
      dockerfile: dev_app.dockerfile
      args:
          - USER_ID
          - GROUP_ID
      context: .
    image: nlp_demo_dev_app:0.0.1
    command: ${cmd}
    working_dir: "/app/$APP_NAME"
    volumes:
      - "$PWD:/app"

  profile-serve-built-app:
    build: 
      dockerfile: build.dockerfile
      context: .
    image: nlp_demo_build_app:0.0.1
    ports: 
      - "127.0.0.1:5000:5000"
    environment:
      PUBLIC_URL: "/"
    init: true
    command: ["npx", "serve", "-s", "build"]

  production-build-app:
    build: 
      dockerfile: build.dockerfile
      args:
          - USER_ID
          - GROUP_ID
      context: .
    image: nlp_demo_build_app:0.0.1
    environment:
      PUBLIC_URL: "https://ucrel-web.lancs.ac.uk/demo"
    volumes:
      - "$PWD:/app"

