name: build website

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ./web_demo/nlp_demo/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./web_demo/nlp_demo/package-lock.json') }}
          restore-keys: ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          cd ./web_demo/nlp_demo
          npm install
      - name: build
        run: |
          cd ./web_demo/nlp_demo
          yarn build
      - name: test
        run: |
          cd ./web_demo/nlp_demo
          ls -al build